/// Flutter icons WarezIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WarezIcons
///      fonts:
///       - asset: fonts/WarezIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WarezIcons {
  WarezIcons._();

  static const _kFontFam = 'WarezIcons';
  static const String? _kFontPkg = null;

  static const IconData fitgirl = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goggames = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
